In [109]:
import pandas as pd

In [110]:
df = pd.read_csv("/content/skoob_todos_livros.csv")

In [111]:
df

,Título do Livro,Autor,Quantidade de Páginas,Tempo de Leitura,Nota Média,Leram,Lendo,Querem,Relendo,Abandonos,Resenhas,Favoritos,Avaliaram
0,Alchemised [Edição brasileira] -,SenLinYu,900 páginas,1d 6h 0m,4.5,9155.0,4786.0,46897.0,43.0,590.0,2373.0,1646.0,6826.0
1,Sorte No Amor -,Lynn Painter,256 páginas,8h 32m,3.9,10264.0,1197.0,41474.0,53.0,362.0,1887.0,450.0,6392.0
2,Querida tia -,Valérie Perrin,496 páginas,16h 32m,4.1,2917.0,720.0,18831.0,14.0,138.0,637.0,171.0,2006.0
3,MURDLE: A ESCOLA DE MISTÉRIOS - 50 enigmas de ...,G. T. Karber,240 páginas,8h 0m,4.1,223.0,174.0,3733.0,12.0,30.0,9.0,16.0,42.0
4,Férias de matar -,Tessa Bailey,288 páginas,9h 36m,3.5,3171.0,408.0,14336.0,19.0,205.0,573.0,85.0,2146.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12811,Missão: Seduzir (The Mistress Assigment) (Swee...,Penny Jordan,256 páginas,8h 32m,3.4,60.0,2.0,26.0,3.0,2.0,1.0,0.0,50.0
12812,Ensaio sobre a cegueira -,José Saramago,312 páginas,10h 24m,4.5,91474.0,6502.0,78225.0,162.0,3183.0,4827.0,7413.0,44435.0
12813,Um copo de cólera -,Raduan Nassar,88 páginas,2h 56m,3.8,4679.0,105.0,2031.0,10.0,71.0,199.0,108.0,2796.0
12814,O professor de desejo -,Philip Roth,214 páginas,7h 8m,3.8,508.0,25.0,412.0,4.0,21.0,22.0,1.0,314.0
12815,"Nasce Um Empreendedor - Dicas, provocações e r...",Bob Wollheim e Dony de Nuccio,184 páginas,6h 8m,3.7,61.0,11.0,160.0,0.0,4.0,4.0,2.0,42.0

In [112]:
#tira a palavra 'páginas' da string
df['Quantidade de Páginas'] = df['Quantidade de Páginas'].str.replace('páginas', '')

In [113]:
#função que converte o tempo para Minutos
def conversorTempo(celula):

  num = ''
  tempo = 0


  for char in str(celula):
    if char.isdigit():
      num += char
    else:
      if char == 'd':
        tempo += int(num) * 1440
      elif char == 'h':
        tempo += int(num) * 60
      elif char == 'm':
        tempo += int(num)
      num = ''

  return tempo

In [114]:
#aplica a função e troca o nome
df['Tempo de Leitura'] = df['Tempo de Leitura'].apply(conversorTempo)
df.rename(columns={'Tempo de Leitura': 'Tempo de Leitura (Minutos)'}, inplace=True)

In [115]:
#tira os valores vazios
df[df['Título do Livro'].isna()]

df = df.dropna().reset_index(drop=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12802 entries, 0 to 12801
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Título do Livro             12802 non-null  object
 1   Autor                       12802 non-null  object
 2   Quantidade de Páginas       12802 non-null  object
 3   Tempo de Leitura (Minutos)  12802 non-null  int64
 4   Nota Média                  12802 non-null  float64
 5   Leram                       12802 non-null  float64
 6   Lendo                       12802 non-null  float64
 7   Querem                      12802 non-null  float64
 8   Relendo                     12802 non-null  float64
 9   Abandonos                   12802 non-null  float64
 10  Resenhas                    12802 non-null  float64
 11  Favoritos                   12802 non-null  float64
 12  Avaliaram                   12802 non-null  float64
dtypes: float64(9), int64(1), object(3)
memory usage: 1.3+ MB

In [116]:
#passa a coluna pra int
df['Quantidade de Páginas'] = df['Quantidade de Páginas'].astype(int)

In [117]:
#tira os hífens do final do nome
df['Título do Livro'] = df['Título do Livro'].str.rstrip('-')

In [118]:
df

,Título do Livro,Autor,Quantidade de Páginas,Tempo de Leitura (Minutos),Nota Média,Leram,Lendo,Querem,Relendo,Abandonos,Resenhas,Favoritos,Avaliaram
0,Alchemised [Edição brasileira],SenLinYu,900,1800,4.5,9155.0,4786.0,46897.0,43.0,590.0,2373.0,1646.0,6826.0
1,Sorte No Amor,Lynn Painter,256,512,3.9,10264.0,1197.0,41474.0,53.0,362.0,1887.0,450.0,6392.0
2,Querida tia,Valérie Perrin,496,992,4.1,2917.0,720.0,18831.0,14.0,138.0,637.0,171.0,2006.0
3,MURDLE: A ESCOLA DE MISTÉRIOS - 50 enigmas de ...,G. T. Karber,240,480,4.1,223.0,174.0,3733.0,12.0,30.0,9.0,16.0,42.0
4,Férias de matar,Tessa Bailey,288,576,3.5,3171.0,408.0,14336.0,19.0,205.0,573.0,85.0,2146.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12797,Missão: Seduzir (The Mistress Assigment) (Swee...,Penny Jordan,256,512,3.4,60.0,2.0,26.0,3.0,2.0,1.0,0.0,50.0
12798,Ensaio sobre a cegueira,José Saramago,312,624,4.5,91474.0,6502.0,78225.0,162.0,3183.0,4827.0,7413.0,44435.0
12799,Um copo de cólera,Raduan Nassar,88,176,3.8,4679.0,105.0,2031.0,10.0,71.0,199.0,108.0,2796.0
12800,O professor de desejo,Philip Roth,214,428,3.8,508.0,25.0,412.0,4.0,21.0,22.0,1.0,314.0
12801,"Nasce Um Empreendedor - Dicas, provocações e r...",Bob Wollheim e Dony de Nuccio,184,368,3.7,61.0,11.0,160.0,0.0,4.0,4.0,2.0,42.0